프록시, 통신사 아이피 제한(비회원 제한)
organization/KotlinInside pull request #104
Opened 2022-02-15 01:55 UTC by wipproject

날짜는 yyyy.MM.dd HH:mm 형식으로 현재 시간 기준 48시간, 1시간, 48시간을 초과해서 적용 할 수 없습니다.
이미지 동영상 첨부는 VPN,통신사IP는 각각 P, M 이며
동시 적용을 원할시 P,M 식으로 값을 적어주면 됩니다.

2022-02-15 09:36 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgDate: String,
`Date`와 `SimpleDateFormat`을 활용하는 것이 좋아보입니다.

2022-02-15 09:37 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +            throw RuntimeException("유동닉은 갤러리 관리를 할 수 없습니다.")
`RuntimeException`에서 `IllegalStateException`로 대체 예정

2022-02-15 09:40 UTC, JellyBrick requested changes

2022-02-15 09:40 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +                    .addBodyParameter("imgDate", imgDate)
위 코멘트와 동일한 내용, `SimpleDateFormat` 활용

2022-02-15 09:40 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgDate: String,
`Date`와 `SimpleDateFormat`을 활용하는 것이 좋아보입니다.

2022-02-15 09:40 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgStatus: String
`enum class` 활용하는 것이 좋아보입니다.

2022-02-15 09:40 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgStatus: String
해당 인자들이 모두 필수 인자인가요?
값이 비어있는 경우 어떤 동작을 하는지 알려주실 수 있나요?

2022-02-15 15:18 UTC, merged

2022-02-15 16:26 UTC, wipproject commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgStatus: String
값이 비어있는경우 사용안함(해제) 상태가 됩니다

2022-02-15 16:26 UTC, wipproject commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgStatus: String
죄송합니다

2022-02-15 16:35 UTC, wipproject commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgStatus: String
추가로 imgStatus 의 값의 경우 A를 주면 전체 유동의 이미지 차단이 됩니다, imgStatus를 설정 해 줄경우 imgDate는 필수 인자가 됩니다, imgDate 값을 주지 않으면 설정 자체가 불가능 하므로 적용이 안될것으로 추측됩니다

2022-02-15 19:53 UTC, JellyBrick commented on src/main/kotlin/be/zvz/kotlininside/api/management/NoMemberBlock.kt
> +        private val imgStatus: String
> 죄송합니다

괜찮습니다! 단순히 코드 리뷰만 한 것이니 별 신경 안 쓰셔도 됩니다!

2022-02-15 19:58 UTC, JellyBrick commented
@wipproject 혹시 `"${ApiUrl.Gallery.MINOR_NOMEMBER}/${gallId}"` 호출 시 어떤 형태의 JSON이 반환되는지 알고계신가요?

## 실패시

```json
{
    "result": false,
    "cause": "원인"
}
```

## 성공시

```json
{
    "result": true,
    "cause": "성공 및 결과 string"
}
```

이 형태가 맞나요?

2022-02-16 00:16 UTC, wipproject commented
성공시 {"msg":"","result":"success"}를 반환합니다
실패는 잠시 후에 체크해 보겠습니다.

2022-02-16 00:18 UTC, wipproject commented
msg 는 테스트때 제가 한눈에 보기 위해서 추가한것입니다 코드 빼는걸 까먹었군요